// Generated by tools/sf2_to_amy.py -- GM SoundFont ROM bank.
#ifndef __PCM_H
#define __PCM_H
#define PCM_AMY_SAMPLE_RATE 44100
#define PCM_BASE_SAMPLES 189
#define PCM_BASE_LENGTH 3534694
#define PCM_WAVETABLE_BASE PCM_BASE_SAMPLES
#define PCM_WAVETABLE_SAMPLES 0
#define PCM_WAVETABLE_LEN 0
#define PCM_LENGTH PCM_BASE_LENGTH
#define PCM_MAP_ENTRIES PCM_BASE_SAMPLES
#include "pcm_samples_tiny.h"
const uint16_t pcm_samples = PCM_MAP_ENTRIES;
const uint16_t pcm_wavetable_base = PCM_WAVETABLE_BASE;
const uint16_t pcm_wavetable_samples = PCM_WAVETABLE_SAMPLES;
const uint32_t pcm_wavetable_len = PCM_WAVETABLE_LEN;
const pcm_map_t pcm_map[PCM_MAP_ENTRIES] PROGMEM = {
    {0, 65738, 54267, 65722, 59}, /* [0] Grand Piano (# GD BOS B3 15) */
    {65738, 65738, 54267, 65722, 59}, /* [1] Bright Grand (# GD BOS B3 15) */
    {131476, 65661, 54267, 65645, 59}, /* [2] Electric Gra (# GD BOS B3 15) */
    {197137, 65738, 54267, 65722, 59}, /* [3] Honky-Tonk P (# GD BOS B3 15) */
    {262875, 105953, 73079, 105950, 60}, /* [4] Tine Electri (# Crystal Rhodes) */
    {368828, 105953, 73079, 105950, 60}, /* [5] FM Electric  (# Crystal Rhodes) */
    {474781, 59229, 56669, 59213, 61}, /* [6] Harpsichord (# HChord Med) */
    {534010, 14074, 13725, 14058, 60}, /* [7] Clavinet (# Clavinet Med) */
    {548084, 13380, 12606, 13364, 65}, /* [8] Celeste (# Celesta) */
    {561464, 15321, 14802, 15305, 65}, /* [9] Glockenspiel (# Glock Ambient) */
    {576785, 37459, 37274, 37443, 60}, /* [10] Music Box (# Musicbox Hi) */
    {614244, 937, 860, 929, 75}, /* [11] Vibraphone (@ Vibes E2) */
    {615181, 2321, 2180, 2305, 65}, /* [12] Marimba (# Marimba) */
    {617502, 7497, 0, 7497, 65}, /* [13] Xylophone (# Xylophone) */
    {624999, 5479, 4818, 5471, 86}, /* [14] Tubular Bell (@ TubeBell D4) */
    {630478, 23737, 23422, 23721, 62}, /* [15] Dulcimer (# Dulcimer Med) */
    {654215, 270, 50, 262, 68}, /* [16] Tonewheel Or (@ DrawBar Organ C3) */
    {654485, 1480, 1350, 1472, 78}, /* [17] Percussive O (@ Perc Organ C4) */
    {655965, 5699, 6, 5691, 79}, /* [18] Rock Organ (@ Organ 3 C3) */
    {661664, 2465, 2319, 2457, 75}, /* [19] Pipe Organ (@ Church Org C3) */
    {664129, 795, 727, 787, 78}, /* [20] Reed Organ (@ Accordion 2) */
    {664924, 795, 727, 787, 78}, /* [21] Accordion (@ Accordion 2) */
    {665719, 1105, 1023, 1097, 74}, /* [22] Harmonica (@ Harmonica 2) */
    {666824, 795, 727, 787, 78}, /* [23] Bandoneon (@ Accordion 2) */
    {667619, 37461, 36014, 37445, 59}, /* [24] Nylon Guitar (# Nylon Gtr. 5) */
    {705080, 84082, 83353, 84066, 47}, /* [25] Steel Guitar (# Steel Gtr. 4) */
    {789162, 736, 635, 728, 70}, /* [26] Jazz Guitar (@ Jazz Guitar Bb2) */
    {789898, 1647, 1554, 1639, 72}, /* [27] Clean Guitar (@ Strat Db3) */
    {791545, 1193, 1096, 1185, 71}, /* [28] Muted Guitar (@ Gtr Mute B2) */
    {792738, 57304, 57120, 57288, 60}, /* [29] Overdrive Gu (# Metal Gtr C5) */
    {850042, 57304, 57120, 57288, 60}, /* [30] Distortion G (# Metal Gtr C5) */
    {907346, 1331, 1139, 1323, 81}, /* [31] Guitar Harmo (@ Gtr Harmonics B2) */
    {908677, 14445, 13924, 14429, 41}, /* [32] Acoustic Bas (# Accoustic Bass v2) */
    {923122, 6322, 5803, 6306, 41}, /* [33] Finger Bass (# Fingered Bass v2) */
    {929444, 8835, 8313, 8819, 41}, /* [34] Pick Bass (# Picked Bass v2) */
    {938279, 267, 194, 259, 88}, /* [35] Fretless Bas (@ Fretless BassDb3) */
    {938546, 12510, 11742, 12494, 34}, /* [36] Slap Bass 1 (# Slap Bass v2) */
    {951056, 12510, 11742, 12494, 34}, /* [37] Slap Bass 2 (# Slap Bass v2) */
    {963566, 18950, 17926, 18934, 41}, /* [38] Synth Bass 1 (# Synth Bass v2) */
    {982516, 18950, 17926, 18934, 41}, /* [39] Synth Bass 2 (# Synth Bass v2) */
    {1001466, 1306, 1205, 1299, 70}, /* [40] Violin (@ Violin Bb2) */
    {1002772, 1593, 1510, 1585, 74}, /* [41] Viola (@ Violin D3) */
    {1004365, 9934, 9770, 9918, 62}, /* [42] Cello (# Cello Hi) */
    {1014299, 2553, 2245, 2545, 50}, /* [43] Double Bass (@ ContraBass D1) */
    {1016852, 26232, 12249, 26224, 65}, /* [44] Tremolo Stri (# Strings 2) */
    {1043084, 9437, 9250, 9421, 60}, /* [45] Pizzicato St (# Pizzicato Lo31) */
    {1052521, 17178, 16713, 17162, 62}, /* [46] Orchestral H (# Harp 2) */
    {1069699, 22491, 0, 22491, 54}, /* [47] Timpani (# Timpani 2) */
    {1092190, 26232, 12249, 26224, 65}, /* [48] Fast Strings (# Strings 2) */
    {1118422, 26232, 12249, 26224, 65}, /* [49] Slow Strings (# Strings 2) */
    {1144654, 62523, 12058, 62507, 65}, /* [50] Synth String (# Synth Strings) */
    {1207177, 62523, 12058, 62507, 65}, /* [51] Synth String (# Synth Strings) */
    {1269700, 55075, 27180, 55059, 53}, /* [52] Concert Choi (# Female Aahs 1) */
    {1324775, 6542, 0, 6542, 60}, /* [53] Voice Oohs (# Doo 1) */
    {1331317, 9955, 3, 9947, 76}, /* [54] Synth Voice (@ SynVox Gb3) */
    {1341272, 12959, 0, 12959, 88}, /* [55] Orchestra Hi (@ OrchHit C5) */
    {1354231, 17350, 16832, 17334, 60}, /* [56] Trumpet (# Trumpet X Lo1) */
    {1371581, 14783, 13762, 14767, 48}, /* [57] Trombone (# Tuba Hi) */
    {1386364, 14783, 13762, 14767, 48}, /* [58] Tuba (# Tuba Hi) */
    {1401147, 1148, 1034, 1140, 68}, /* [59] Muted Trumpe (@ Harmon Mute C3) */
    {1402295, 99220, 86550, 99204, 53}, /* [60] French Horns (# Horn 4) */
    {1501515, 17961, 6126, 17945, 64}, /* [61] Brass Sectio (# Brass Lo) */
    {1519476, 30659, 30541, 30643, 69}, /* [62] Synth Brass  (# Synth Brass) */
    {1550135, 30659, 30541, 30643, 69}, /* [63] Synth Brass  (# Synth Brass) */
    {1580794, 12526, 3793, 12510, 68}, /* [64] Soprano Sax (# Soprano Sax C21) */
    {1593320, 11277, 9746, 11261, 60}, /* [65] Alto Sax (# Alto Sax C4) */
    {1604597, 16831, 13259, 16815, 75}, /* [66] Tenor Sax (# Tenor Sax C31) */
    {1621428, 10545, 10410, 10529, 66}, /* [67] Baritone Sax (# Bari Sax A#21) */
    {1631973, 25653, 22058, 25637, 67}, /* [68] Oboe (# Oboe 1) */
    {1657626, 790, 699, 782, 72}, /* [69] English Horn (@ English Horn Db3) */
    {1658416, 839, 741, 831, 71}, /* [70] Bassoon (@ Bassoon C3) */
    {1659255, 22636, 12978, 22620, 58}, /* [71] Clarinet (# Clari Lo2) */
    {1681891, 75859, 2246, 75843, 76}, /* [72] Piccolo (# Recorder Hi) */
    {1757750, 48712, 41003, 48696, 61}, /* [73] Flute (# Flute c4) */
    {1806462, 62427, 2231, 62411, 64}, /* [74] Recorder (# Recorder Lo) */
    {1868889, 8390, 1570, 8382, 77}, /* [75] Pan Flute (@ Pan Flute Med) */
    {1877279, 5313, 0, 5313, 70}, /* [76] Bottle Blow (sikue2) */
    {1882592, 7467, 2085, 7463, 81}, /* [77] Shakuhachi (shakua2) */
    {1890059, 1804, 1660, 1788, 65}, /* [78] Whistle (# Ocarina) */
    {1891863, 1804, 1660, 1788, 65}, /* [79] Ocarina (# Ocarina) */
    {1893667, 179, 3, 171, 59}, /* [80] Square Lead (@ Square Wave C2) */
    {1893846, 179, 3, 171, 60}, /* [81] Saw Lead (@ Saw Wave 1 C2) */
    {1894025, 5313, 0, 5313, 70}, /* [82] Synth Callio (sikue2) */
    {1899338, 5313, 0, 5313, 70}, /* [83] Chiffer Lead (sikue2) */
    {1904651, 179, 3, 171, 60}, /* [84] Charang (@ Saw Wave 1 C2) */
    {1904830, 5435, 129, 5427, 98}, /* [85] Solo Vox (@ Solo Vox C5) */
    {1910265, 26232, 12249, 26224, 65}, /* [86] 5th Saw Wave (# Strings 2) */
    {1936497, 2182, 1639, 2174, 40}, /* [87] Bass & Lead (@ SawBassWave C1) */
    {1938679, 4878, 26, 4870, 83}, /* [88] Fantasia (@ Spectrum Eb5) */
    {1943557, 26232, 12249, 26224, 65}, /* [89] Warm Pad (# Strings 2) */
    {1969789, 26232, 12249, 26224, 65}, /* [90] Polysynth (# Strings 2) */
    {1996021, 4878, 26, 4870, 95}, /* [91] Space Voice (@ Spectrum Eb5) */
    {2000899, 4878, 26, 4870, 95}, /* [92] Bowed Glass (@ Spectrum Eb5) */
    {2005777, 1647, 1554, 1639, 72}, /* [93] Metal Pad (@ Strat Db3) */
    {2007424, 9955, 3, 9947, 76}, /* [94] Halo Pad (@ SynVox Gb3) */
    {2017379, 26232, 12249, 26224, 65}, /* [95] Sweep Pad (# Strings 2) */
    {2043611, 26232, 12249, 26224, 65}, /* [96] Ice Rain (# Strings 2) */
    {2069843, 26232, 12249, 26224, 65}, /* [97] Soundtrack (# Strings 2) */
    {2096075, 13380, 12606, 13364, 65}, /* [98] Crystal (# Celesta) */
    {2109455, 37461, 36014, 37445, 59}, /* [99] Atmosphere (# Nylon Gtr. 5) */
    {2146916, 26232, 12249, 26224, 65}, /* [100] Brightness (# Strings 2) */
    {2173148, 9955, 3, 9947, 76}, /* [101] Goblin (@ SynVox Gb3) */
    {2183103, 55075, 27180, 55059, 53}, /* [102] Echo Drops (# Female Aahs 1) */
    {2238178, 26232, 12249, 26224, 65}, /* [103] Star Theme (# Strings 2) */
    {2264410, 1570, 1488, 1562, 74}, /* [104] Sitar (@ Sitar Eb3) */
    {2265980, 27874, 0, 27874, 64}, /* [105] Banjo (# Banjo) */
    {2293854, 1205, 1102, 1197, 70}, /* [106] Shamisen (@ Shamisen C3) */
    {2295059, 12438, 12251, 12422, 60}, /* [107] Koto (# Koto Lo) */
    {2307497, 2200, 2024, 2192, 72}, /* [108] Kalimba (@ Kalimba C3) */
    {2309697, 1041, 976, 1033, 79}, /* [109] Bagpipes (@ Bagpipe Bb3) */
    {2310738, 1306, 1205, 1299, 70}, /* [110] Fiddle (@ Violin Bb2) */
    {2312044, 790, 699, 782, 72}, /* [111] Shenai (@ English Horn Db3) */
    {2312834, 69, 17, 65, 84}, /* [112] Tinker Bell (coldglass7wave) */
    {2312903, 2297, 2123, 2289, 84}, /* [113] Agogo (@ Agogo Bell) */
    {2315200, 4799, 4661, 4791, 76}, /* [114] Steel Drums (@ SteelDrum D3) */
    {2319999, 851, 0, 851, 92}, /* [115] Wood Block ($ Wood Block) */
    {2320850, 17779, 17227, 17763, 64}, /* [116] Taiko Drum (# Taiko Y) */
    {2338629, 10766, 9618, 10758, 67}, /* [117] Melodic Tom (@ Acoustic Tom) */
    {2349395, 1320, 1230, 1313, 114}, /* [118] Synth Drum (@ Syn Drum Wave) */
    {2350715, 12031, 3807, 12024, 72}, /* [119] Reverse Cymb (# Reverse Cymb. Loop) */
    {2362746, 3417, 0, 3417, 75}, /* [120] Fret Noise (@ FretNoise) */
    {2366163, 8390, 1570, 8382, 77}, /* [121] Breath Noise (@ Pan Flute Med) */
    {2374553, 14028, 6, 14020, 83}, /* [122] Seashore (@ PinkNoiseWave) */
    {2388581, 2718, 1149, 2710, 99}, /* [123] Birds (@ Bird) */
    {2391299, 1270, 36, 1263, 78}, /* [124] Telephone 1 (@ Telephone) */
    {2392569, 4165, 3, 4157, 88}, /* [125] Helicopter (@ Helicopter) */
    {2396734, 8690, 9, 8682, 86}, /* [126] Applause (@ Applause) */
    {2405424, 10420, 0, 10420, 82}, /* [127] Gun Shot (@ Gun Shot) */
    {2415844, 1339, 0, 1339, 27}, /* [128] Drum 27 ($ Hi-Q) */
    {2417183, 14600, 0, 14600, 28}, /* [129] Drum 28 ($ Shaker) */
    {2431783, 10596, 0, 10596, 29}, /* [130] Drum 29 ($ Scratch Low  D053) */
    {2442379, 3416, 0, 3416, 30}, /* [131] Drum 30 ($ Scratch High  D063) */
    {2445795, 8929, 0, 8929, 31}, /* [132] Drum 31 ($ Sticks) */
    {2454724, 72, 0, 72, 33}, /* [133] Drum 32 ($ Sinetick) */
    {2454796, 802, 0, 802, 43}, /* [134] Drum 33 ($ Click808) */
    {2455598, 802, 0, 802, 44}, /* [135] Drum 34 ($ Click808) */
    {2456400, 22032, 0, 22032, 35}, /* [136] Drum 35 ($ Kick 1 NG) */
    {2478432, 22032, 0, 22032, 35}, /* [137] Drum 36 ($ Kick 1 NG) */
    {2500464, 6050, 0, 6050, 35}, /* [138] Drum 37 ($ Rim 1) */
    {2506514, 33056, 0, 33056, 38}, /* [139] Drum 38 ($ Snare 1 NT 2) */
    {2539570, 12448, 0, 12448, 39}, /* [140] Drum 39 ($ Clap NG) */
    {2552018, 33120, 0, 33120, 40}, /* [141] Drum 40 ($ Snare 2 NT v4) */
    {2585138, 33075, 0, 33075, 41}, /* [142] Drum 41 ($ Low Tom 2  NT 3) */
    {2618213, 22066, 0, 22066, 42}, /* [143] Drum 42 ($ HiHat Closed1) */
    {2640279, 33075, 0, 33075, 43}, /* [144] Drum 43 ($ Low Tom  1 NT 3) */
    {2673354, 22066, 0, 22066, 45}, /* [145] Drum 44 ($ HiHat Closed1) */
    {2695420, 33075, 0, 33075, 43}, /* [146] Drum 45 ($ Low Tom 2  NT 3) */
    {2728495, 32483, 0, 32483, 46}, /* [147] Drum 46 ($ HiHat Open1) */
    {2760978, 33075, 0, 33075, 45}, /* [148] Drum 47 ($ Low Tom  1 NT 3) */
    {2794053, 33075, 0, 33075, 44}, /* [149] Drum 48 ($ Low Tom 2  NT 3) */
    {2827128, 65223, 0, 65223, 52}, /* [150] Drum 49 ($ Crash Lo v2) */
    {2892351, 33075, 0, 33075, 46}, /* [151] Drum 50 ($ Low Tom  1 NT 3) */
    {2925426, 52540, 0, 52540, 51}, /* [152] Drum 51 ($ Ride NG) */
    {2977966, 65522, 0, 65522, 55}, /* [153] Drum 52 ($ Crash Hi v2) */
    {3043488, 42834, 0, 42834, 55}, /* [154] Drum 53 ($ Bell NG) */
    {3086322, 3267, 0, 3267, 64}, /* [155] Drum 54 ($ Brass Tambourine) */
    {3089589, 65223, 0, 65223, 57}, /* [156] Drum 55 ($ Crash Lo v2) */
    {3154812, 6139, 0, 6139, 58}, /* [157] Drum 56 ($ Cowbell  A024) */
    {3160951, 65522, 0, 65522, 59}, /* [158] Drum 57 ($ Crash Hi v2) */
    {3226473, 54072, 0, 54072, 58}, /* [159] Drum 58 ($ Vibraslap 2) */
    {3280545, 52540, 0, 52540, 61}, /* [160] Drum 59 ($ Ride NG) */
    {3333085, 5802, 0, 5802, 60}, /* [161] Drum 60 ($ Bongo High  C103) */
    {3338887, 5973, 0, 5973, 61}, /* [162] Drum 61 ($ Bongo Low  C093) */
    {3344860, 8587, 0, 8587, 62}, /* [163] Drum 62 ($ Conga Side  C073) */
    {3353447, 3100, 0, 3100, 63}, /* [164] Drum 63 ($ Conga High  C083) */
    {3356547, 12983, 0, 12983, 64}, /* [165] Drum 64 ($ Conga Low  C063) */
    {3369530, 17175, 0, 17175, 65}, /* [166] Drum 65 ($ Timbale High  C123) */
    {3386705, 14744, 0, 14744, 66}, /* [167] Drum 66 ($ Timbale Low  C113) */
    {3401449, 10550, 0, 10550, 67}, /* [168] Drum 67 ($ Agogo High  C043) */
    {3411999, 10759, 0, 10759, 68}, /* [169] Drum 68 ($ Agogo Low  C033) */
    {3422758, 4396, 0, 4396, 69}, /* [170] Drum 69 ($ Shaker Short) */
    {3427154, 3267, 0, 3267, 78}, /* [171] Drum 70 ($ Brass Tambourine) */
    {3430421, 4057, 0, 4057, 71}, /* [172] Drum 71 ($ Whistle Short) */
    {3434478, 16688, 0, 16688, 72}, /* [173] Drum 72 ($ Whistle Long) */
    {3451166, 1976, 0, 1976, 73}, /* [174] Drum 73 ($ Guiro Short) */
    {3453142, 13051, 0, 13051, 74}, /* [175] Drum 74 ($ Guiro Long) */
    {3466193, 3236, 0, 3236, 75}, /* [176] Drum 75 ($ Clavs  B054) */
    {3469429, 851, 0, 851, 86}, /* [177] Drum 76 ($ Wood Block) */
    {3470280, 851, 0, 851, 92}, /* [178] Drum 77 ($ Wood Block) */
    {3471131, 9987, 0, 9987, 76}, /* [179] Drum 78 ($ Yaw) */
    {3481118, 5621, 0, 5621, 80}, /* [180] Drum 79 ($ Yow) */
    {3486739, 2068, 0, 2068, 88}, /* [181] Drum 80 ($ Triangle) */
    {3488807, 2068, 0, 2068, 93}, /* [182] Drum 81 ($ Triangle) */
    {3490875, 4396, 0, 4396, 79}, /* [183] Drum 82 ($ Shaker Short) */
    {3495271, 1501, 0, 1501, 98}, /* [184] Drum 83 ($ Sleigh Bells) */
    {3496772, 7012, 0, 7012, 98}, /* [185] Drum 84 ($ Bell Tree) */
    {3503784, 1422, 0, 1422, 97}, /* [186] Drum 85 ($ Castanets) */
    {3505206, 14744, 0, 14744, 87}, /* [187] Drum 86 ($ Timbale Low  C113) */
    {3519950, 14744, 0, 14744, 102}, /* [188] Drum 87 ($ Timbale Low  C113) */
};
#endif // __PCM_H
