// Generated by tools/sf2_to_amy.py -- GM program/drum -> AMY preset map.
#pragma once
#include <Arduino.h>

// AMY PCM preset index for each GM program (0..127).
static const uint8_t GM_PROGRAM_PRESET[128] PROGMEM = {
      0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
     16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
     32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
     48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
     64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
     80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
     96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
    112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
};

// AMY PCM preset index for each GM drum note (255 = none).
static const uint8_t GM_DRUM_PRESET[128] PROGMEM = {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 128, 129, 130, 131, 132,
    133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
    149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
    165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
    181, 182, 183, 184, 185, 186, 187, 188, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
};

#define GM_NUM_PRESETS 189

// Recorded root note of each preset's sample.
static const uint8_t GM_PRESET_ROOT[GM_NUM_PRESETS] PROGMEM = {
     59,  59,  59,  59,  60,  60,  61,  60,  65,  65,  60,  75,  65,  65,  86,  62,
     68,  78,  79,  75,  78,  78,  74,  78,  59,  47,  70,  72,  71,  60,  60,  81,
     41,  41,  41,  88,  34,  34,  41,  41,  70,  74,  62,  50,  65,  60,  62,  54,
     65,  65,  65,  65,  53,  60,  76,  88,  60,  48,  48,  68,  53,  64,  69,  69,
     68,  60,  75,  66,  67,  72,  71,  58,  76,  61,  64,  77,  70,  81,  65,  65,
     59,  60,  70,  70,  60,  98,  65,  40,  83,  65,  65,  95,  95,  72,  76,  65,
     65,  65,  65,  59,  65,  76,  53,  65,  74,  64,  70,  60,  72,  79,  70,  72,
     84,  84,  76,  92,  64,  67, 114,  72,  75,  77,  83,  99,  78,  88,  86,  82,
     27,  28,  29,  30,  31,  33,  43,  44,  35,  35,  35,  38,  39,  40,  41,  42,
     43,  45,  43,  46,  45,  44,  52,  46,  51,  55,  55,  64,  57,  58,  59,  58,
     61,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  78,  71,  72,  73,  74,
     75,  86,  92,  76,  80,  88,  93,  79,  98,  98,  97,  87, 102,
};

// 1 = preset has a sustain loop; 0 = one-shot (percussive).
static const uint8_t GM_PRESET_LOOPED[GM_NUM_PRESETS] PROGMEM = {
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,
      1,   1,   1,   1,   1,   0,   1,   0,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   1,   1,   1,
      1,   1,   0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   0,   1,   1,   1,   1,   1,   1,
      1,   1,   1,   0,   1,   1,   1,   1,   0,   1,   1,   1,   1,   1,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
};

// GM program names (<=12 chars) for the UI.
static const char* const GM_NAMES[128] = {
    "Grand Piano", "Bright Grand", "Electric Gra", "Honky-Tonk P",
    "Tine Electri", "FM Electric ", "Harpsichord", "Clavinet",
    "Celeste", "Glockenspiel", "Music Box", "Vibraphone",
    "Marimba", "Xylophone", "Tubular Bell", "Dulcimer",
    "Tonewheel Or", "Percussive O", "Rock Organ", "Pipe Organ",
    "Reed Organ", "Accordion", "Harmonica", "Bandoneon",
    "Nylon Guitar", "Steel Guitar", "Jazz Guitar", "Clean Guitar",
    "Muted Guitar", "Overdrive Gu", "Distortion G", "Guitar Harmo",
    "Acoustic Bas", "Finger Bass", "Pick Bass", "Fretless Bas",
    "Slap Bass 1", "Slap Bass 2", "Synth Bass 1", "Synth Bass 2",
    "Violin", "Viola", "Cello", "Double Bass",
    "Tremolo Stri", "Pizzicato St", "Orchestral H", "Timpani",
    "Fast Strings", "Slow Strings", "Synth String", "Synth String",
    "Concert Choi", "Voice Oohs", "Synth Voice", "Orchestra Hi",
    "Trumpet", "Trombone", "Tuba", "Muted Trumpe",
    "French Horns", "Brass Sectio", "Synth Brass ", "Synth Brass ",
    "Soprano Sax", "Alto Sax", "Tenor Sax", "Baritone Sax",
    "Oboe", "English Horn", "Bassoon", "Clarinet",
    "Piccolo", "Flute", "Recorder", "Pan Flute",
    "Bottle Blow", "Shakuhachi", "Whistle", "Ocarina",
    "Square Lead", "Saw Lead", "Synth Callio", "Chiffer Lead",
    "Charang", "Solo Vox", "5th Saw Wave", "Bass & Lead",
    "Fantasia", "Warm Pad", "Polysynth", "Space Voice",
    "Bowed Glass", "Metal Pad", "Halo Pad", "Sweep Pad",
    "Ice Rain", "Soundtrack", "Crystal", "Atmosphere",
    "Brightness", "Goblin", "Echo Drops", "Star Theme",
    "Sitar", "Banjo", "Shamisen", "Koto",
    "Kalimba", "Bagpipes", "Fiddle", "Shenai",
    "Tinker Bell", "Agogo", "Steel Drums", "Wood Block",
    "Taiko Drum", "Melodic Tom", "Synth Drum", "Reverse Cymb",
    "Fret Noise", "Breath Noise", "Seashore", "Birds",
    "Telephone 1", "Helicopter", "Applause", "Gun Shot",
};
